### PR TITLE
Integrating tromp solvers into stratum pool miner.

### PR DESCRIPTION
**Pull request by sarath-hotspot**
Integrated tromp equihash algorithm for mining.
Original solvers are available in https://github.com/tromp/equihash

By default tromp equihash is enabled.

How to disable:
In src/libstratum/ZcashStratum.cpp comment following line(17th line).
 #define USE_TROMP_EQUIHASH

Currently N and K are defaulted to 200 & 9. 
To change these values, change trompequihash/equi.h file. 

Note to str4d: 
Sometimes standalone miner is getting blocked. Not working. 
You may want to check.

### CODE REVIEW

**Comment by sammy007** [comment]
Applied locally, this is **amazing**. Now I can't work without it.

**Comment by JanKalin** [comment]
I can confirm that there are problems. I have two machines:
- `Ubuntu 16.04.1 LTS` in a VM with `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609` and
- `Debian GNU/Linux 7.11 (wheezy)` natively with  `gcc (Debian 4.7.2-5) 4.7.2`

Because the Debian's GCC is older, I need to make some edits to get Zcash to compile. However:
- These edits are nowhere near the solver code - see [mydiff.txt](https://github.com/str4d/zcash/files/541473/mydiff.txt)
- I need to make the same edits for both the Zcash official release and str4d's fork for the standalone miner
- Both the Zcash and and the fork work perfectly on both machines, all the tests pass, the zcashd from the official release mines, as does zcash-miner.

But the `zcash-miner` with Tromp's solver works only on the Ubuntu machine - well, it has now been running for around 40 minutes and is still mining. If I run it without arguments, it starts running test solves on Ubuntu, while on Debian it just hangs. If I connect to a stratum server (zec.suprnova.cc or zmine.io) from Debian it segfaults.

Note that Tromp's solver from https://github.com/tromp/equihash works fine on both machines.

**Comment by ivianoo** [comment]
@sammy007 how you have applied locally? can u guide plz

**Comment by str4d** [comment]
Since tromp's miner will be merged into upstream `zcashd`, I'm going to wait until the next release and then merge that into my standalone miner branch to get the solver code. Then I will leverage @sarath-hotspot's changes here to integrate it into my Stratum miner. I'll leave this PR open until then.

**Comment by sammy007** [comment]
@ivianoo need to have git skillz. Add remote `sarath-hotspot`, fetch and merge branch.

**Comment by str4d** [comment]
I have merged v1.0.0-rc2 into my standalone miner, and integrated tromp's solver into the Stratum miner. See `zcash-miner -?` for configuration details.

**Pull request closed without merging**
